brand:
  name: ตะพาบน้ำไต้หวัน ฟาร์ม
  tagline: ศูนย์ความรู้ + การจัดจำหน่ายตะพาบน้ำไต้หวัน เพื่อการเลี้ยงและบริโภคอย่างถูกต้อง
  primaryCtaText: แอดไลน์เพื่อรับคำแนะนำ
  lineId: '@tapabnam.farm'
  lineUrl: https://lin.ee/cBeZNSB
  phone: 0829323965
  facebook: https://www.facebook.com/share/1JmkGWGXWN/
  tiktok: ''
  instagram: ''
  youtube: ''
  address: ''
hero:
  headline: ตะพาบน้ำไต้หวัน ฟาร์ม
  subheadline: เน้นความจริง ไม่ขายฝัน — เริ่มเลี้ยงให้ถูกระบบ ลดพลาด ลดเสียหาย เพิ่มโอกาสไปต่อได้ยาว
  image: /images/hero.jpg
homeSections:
  valueProps:
  - title: ให้ความรู้ก่อนขาย
    desc: อธิบายระบบเลี้ยง น้ำ อาหาร ความเสี่ยง และข้อผิดพลาดที่มือใหม่พลาดบ่อย
    image: /images/value-knowledge.jpg
  - title: สินค้าเป็นระบบ ชัดเจน
    desc: แยกหมวดสินค้า เงื่อนไขชัด ปุ่มสั่ง/ทักไลน์ทุกหน้า
    image: /images/value-products.jpg
  - title: เน้นความเชื่อถือ
    desc: มีรีวิว/หลักฐาน/ขั้นตอนจัดส่ง/นโยบายแบบมืออาชีพ
    image: /images/value-trust.jpg
products:
- slug: juvenile
  name: ลูกตะพาบน้ำไต้หวัน
  priceText: 15 บาท/ตัว
  highlights:
  - ขั้นต่ำ 30 ตัว
  - มีเก็บเงินปลายทาง (COD)
  - รับประกันความเสียหายทุกกรณี (ตามเงื่อนไขที่ระบุ)
  image: /images/p-juvenile.jpg
  ctaText: ทักไลน์เพื่อเช็คคิวรอบส่ง
- slug: meat
  name: เนื้อตะพาบน้ำไต้หวัน
  priceText: 549 บาท/กก.
  highlights:
  - จัดส่งแบบควบคุมอุณหภูมิ
  - เหมาะสำหรับผู้บริโภค/คนชอบเมนูพิเศษ
  image: /images/p-meat.jpg
  ctaText: ทักไลน์เพื่อสั่งซื้อ
- slug: supplies
  name: อาหาร & ยา (สำหรับตะพาบวัยอ่อน)
  priceText: เริ่มต้น 249 บาท
  highlights:
  - อาหารโปรตีน 42% ราคา 249 บาท (ส่งฟรีเมื่อโอน)
  - OXY-100 PRO ราคา 289 บาท (ส่งฟรีเมื่อโอน)
  image: /images/p-supplies.jpg
  ctaText: ทักไลน์เพื่อรับคำแนะนำการใช้
- slug: live-for-cooking
  name: ตะพาบน้ำไต้หวันแบบเป็น ๆ (สำหรับนำไปทำอาหาร)
  priceText: ขายยกลอต
  highlights:
  - ขั้นต่ำ 5 กก. ขึ้นไป
  - ไม่ขายปลีกเป็นตัว
  - 'ลูกค้าหลัก: ร้านอาหาร/ตลาดของสด'
  - สินค้ามีเป็นรอบตามการจับจากบ่อของฟาร์มและบ่อเครือข่ายลูกฟาร์ม
  image: /images/p-live.jpg
  ctaText: ทักไลน์เพื่อเช็คของรอบจับ
faq:
- q: เลี้ยงแล้วขายได้ทันทีไหม?
  a: ตะพาบน้ำไม่ใช่สัตว์เศรษฐกิจที่ซื้อมาเลี้ยงแล้วจะขายได้ทันที ต้องเข้าใจระบบและการวางแผนก่อนเริ่ม
- q: มีรับซื้อคืนไหม?
  a: มีการรับซื้อคืนจริง แต่มีเงื่อนไขเรื่องจำนวนและการรับซื้อตามคิว รายละเอียดไซด์/น้ำหนัก/ราคา
    ขึ้นอยู่กับสภาพตลาดช่วงนั้น ไม่สามารถการันตีล่วงหน้าแบบตายตัวได้
- q: มือใหม่พลาดอะไรบ่อย?
  a: น้ำเสีย โตช้า ตายง่าย และวางแผนตลาดผิด คิดว่ามีตลาดแต่กลับขายไม่ได้ตามคาด — แนะนำเริ่มจาก
    E-book ฟรีและบทความในศูนย์ความรู้
ebooks:
  free:
    title: 'E-Book ฟรี: เริ่มเลี้ยงตะพาบไต้หวันให้ถูกระบบ (ฉบับหยุดก่อนพลาด)'
    subtitle: เหมาะสำหรับมือใหม่ — อ่านจบรู้ทันความเสี่ยง + เช็คลิสต์เตรียมบ่อ
    coverImage: /images/ebook-free.jpg
    bullets:
    - เช็คลิสต์ก่อนเริ่มเลี้ยง (อุปกรณ์/บ่อ/น้ำ)
    - ข้อผิดพลาดที่ทำให้มือใหม่ต้องหยุดกลางทาง
    - แนวทางดูแลเบื้องต้นให้รอดและโตดี
  paid:
    title: คู่มือการเลี้ยงตะพาบน้ำไต้หวัน (ฉบับจริงจัง)
    subtitle: รวมระบบคิด + วิธีเลี้ยงแบบลงรายละเอียด เพื่อให้เริ่มได้อย่างเป็นระบบ
    coverImage: /images/ebook-paid.jpg
    priceText: 500 บาท
    bullets:
    - วางระบบเลี้ยงตั้งแต่น้ำ อาหาร การจัดการ
    - แนวคิดการวางแผนก่อนลงทุน (ไม่ขายฝัน)
    - เหมาะกับคนที่อยากทำจริงและลดโอกาสพลาด
    ctaText: ทักไลน์เพื่อสั่งซื้อ E-book
reviews:
- name: ลูกค้า A
  text: แพ็คดี คำแนะนำละเอียด มือใหม่เข้าใจง่าย
  image: /images/review-1.jpg
- name: ลูกค้า B
  text: ได้ความรู้ก่อนตัดสินใจจริง ทำให้เริ่มเลี้ยงแบบมีระบบ
  image: /images/review-2.jpg
policy:
  disclaimer: ข้อมูลในเว็บไซต์เป็นแนวทางความรู้และประสบการณ์ ไม่ใช่การรับประกันผลลัพธ์
    การเลี้ยงสัตว์มีความเสี่ยงและขึ้นอยู่กับปัจจัยหลายด้าน
